# azure-pipelines.yml
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
      - '*'
pool:
  vmImage: 'ubuntu-latest'
variables:
  maven_version: '3.8.1'
steps:
- script: |
    mkdir mymaven
    cd mymaven
    curl -L https://github.com/saidevops8989/DevOpsClassCodes.git | tar xz
    echo 'pulled from github successfully'
  displayName: 'Checkout code from GitHub'
- script: |
    export MAVEN_HOME=$(pwd)/mymaven
    export PATH=$PATH:$MAVEN_HOME/bin
    mvn -v
    mvn compile
    echo 'converted the code from human readable to machine readable'
  displayName: 'Compile code'
  env:
    MAVEN_OPTS: '-Xmx2048m -XX:MaxPermSize=512m'
- script: |
    mvn test
    echo 'run and execute the test cases'
  displayName: 'Test code'
  env:
    MAVEN_OPTS: '-Xmx2048m -XX:MaxPermSize=512m'
- script: |
    mvn pmd:pmd
    echo 'code review done'
  displayName: 'Code review'
  env:
    MAVEN_OPTS: '-Xmx2048m -XX:MaxPermSize=512m'
- script: |
    mvn package
    echo 'convert the files to war file'
  displayName: 'Package code'
  env:
    MAVEN_OPTS: '-Xmx2048m -XX:MaxPermSize=512m'
- script: |
    BUILD_NUMBER=$(echo $BUILD_NUMBER | sed 's/[^0-9]//g')
    docker build -t devopsstuff09/addressbook:$BUILD_NUMBER .
    docker login
    #docker tag $docker_image_name $(DOCKER_USERNAME)/$docker_image_name:$BUILD_NUMBER
    #docker push $docker_image_name:$BUILD_NUMBER
     docker push devopsstuff09/addressbook:$BUILD_NUMBER
    echo 'docker image built and pushed to Docker Hub'
  displayName: 'Build and push Docker image'
  env:
    DOCKER_REGISTRY_USERNAME: '$(DOCKER_USERNAME)'
    DOCKER_REGISTRY_PASSWORD: '$(DOCKER_REGISTRY_PASSWORD)'
